service:
  name: example1

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8080
      inMemory: true
      migrate: true

provider:
  name: aws

functions:
  functionExample:
    handler: src/functions/functionExample.handler
    events:
      - http:
          path: /functionExample
          method: POST
          cors: true

resources:
  Resources:
    dbExample:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: example_table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S # string
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5 # limite escrita por segundo
          WriteCapacityUnits: 5 # limite leitura por segundo